name: Lint Code, Build, Test and Publish

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    run_linter:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Lint code
              uses: github/super-linter@v5
              env:
                  VALIDATE_ALL_CODEBASE: false
                  DEFAULT_BRANCH: main
                  VALIDATE_CSHARP: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DISABLE_ERRORS: true

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "7.0.x"

            - name: Restore Dependencies
              run: dotnet restore "./CommentAPI/CommentAPI.csproj"

            - name: Restore Test Dependencies
              run: dotnet restore "./CommentAPITests/CommentAPITests.csproj"

            - name: Restore NuGet Packages
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Publish Build Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: built-app
                  path: |
                      CommentAPI/bin/Release/net7.0/
                      CommentAPITests/bin/Release/net7.0/

    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: "7.0.x"
    
        - name: Setup Java for SonarCloud
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'zulu'
    
        - name: Download Build Artifacts
          uses: actions/download-artifact@v3
          with:
            name: built-app
            path: .
    
        - name: SonarCloud Analysis with Code Coverage
          run: |
            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" \
              /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
              /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html 
            dotnet build –no-incremental
            dotnet dotcover test --dcReportType=HTML
            dotnet sonarscanner end /d:sonar.token=""${{ secrets.SONAR_TOKEN }}"
                                    


    publish_to_dockerhub:
      needs: [test]
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Publish - Build and push Docker image
            uses: docker/build-push-action@v5
            with:
                context: .
                file: ./CommentAPI/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/comment_api:main